name: Munir Jalil
favicon: null
layout_spectrum: 0.23713491554372013
typography_spectrum: 0.39164518215693533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.19163840473629534
  lightness: 0.289170358562842
  saturation: 0.7754194408189505
  rhythmicContrast: 0.6476290270220488
purpose: []
